---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
           - 6379:6379
        volumes:
           - ./data:/data
        user: "1000:1000"
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
           - redis-db
        image: jetp104/asteroid_stats:final
        ports:
           - 5000:5000
        environment:
           - REDIS_HOST=redis-db
    worker-app:
        build:
            context: ./
            dockerfile: ./Dockerfile.wrk
        depends_on:
           - redis-db
        image: jetp104/asteroid_worker:final
        environment:
           - REDIS_HOST=redis-db
