---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
           - 6379:6379
        volumes:
           - ./data:/data
        user: "1000:1000"
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ./
            dockerfile: ${PWD}/docker-src/Dockerfile
        depends_on:
           - redis-db
        image: tagower/asteroid_stats:final
        ports:
           - 5000:5000
        environment:
           - REDIS_HOST=redis-db
    asteroid-wrk:
        build:
            context: ./
            dockerfile: ${PWD}/docker-src/Dockerfile.wrk
        depends_on:
           - redis-db
        image: tagower/asteroid_worker:final
        ports:
           - 5000:5000
        environment:
           - REDIS_HOST=redis-db
